version: '3'
services:
  app:
    depends_on:
      - mysql
    build: ./dockerfiles/jS
    ports:
      - 8001:8001
    volumes:
      - .:/app
  mysql:
    build: ./dockerfiles/mysql
    environment:
      MYSQL_USER: blog-user
      MYSQL_ROOT_PASSWORD: RWBYblog
      MYSQL_DATABASE: blog
      MYSQL_DOCKER_PORT: 8080:8081
    ports:
      - 33069:3306 
    volumes:
      - "mysql-data:/var/lib/mysql"
volumes:
  mysql-data:
    driver: "local"