version: '3'
services:
  app:
    depends_on:
      - mysql
    build: ./dockerfiles/jS
    ports:
      - 8001:3000
    volumes:
      - .:/app
  mysql:
    build: ./dockerfiles/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: RWBYblog
      MYSQL_DATABASE: blog
    ports:
      - 3310:3306 
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: "local"